// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfaguilznugwafdfecpl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmYWd1aWx6bnVnd2FmZGZlY3BsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjE5NDAsImV4cCI6MjA2ODQ5Nzk0MH0._dsq9279_bMF8aXBdmMBkdBRgVsNXkZsdGRJSh3Kxqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});